feat: Add TestCases, Email Validation(Duplicated / Registered) (#14)
toppingskorea/toppings-spring-server pull request #17
Opened 2023-05-11 09:21 UTC by h-beeen

# Describe your changes

## Issue ticket number and link (optional)
#15 
## Checklist

- [ ] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [ ] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-05-11 09:22 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/application/user/dto/request/UserSignUpRequest.java
> +    private String userNickName;
name -> userNickName으로 변수명 변경했습니다.
name보다는 nickName이 적절하다고 생각해 수정했는데
다시 깃헙에서 합쳐보니 name -> nickName이 적합할지도 모르게써요.

2023-05-11 09:23 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/application/user/service/UserFindService.java
> +	public User findByUserId(Long UserId) {
UserId로 찾아오는 로직입니다.

2023-05-11 09:23 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/application/user/service/UserSignUpService.java
> +		userValidator.validateUserEmailIsNotDuplicated(user.getUserEmail());
이메일 형식 검증 / 중복 검증 로직 추가

2023-05-11 09:23 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/application/user/service/UserValidator.java
> +
이메일 중복 검사 로직입니다.

2023-05-11 09:24 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/domain/user/User.java
> +	public String getNicknameValue() {
toEntity() 로직입니다.

2023-05-12 13:10 UTC, k-gn requested changes
고생하셨습니다 해빈님!

어제 지옥같은 gradle ci 테스트를 드디어 확인 후 develop에 머지했는데 테스트 코드에 profile 설정을 추가해야대서 코드 충돌이 좀 발생했네요! 이부분 수정 한번 부탁드립니다!

2023-05-12 13:10 UTC, k-gn commented on core/src/test/java/kr/co/toppings/core/user/domain/UserEmailTest.java
> +		);
다양하게 부적합한 경우를 검증하신 것 좋습니다!

2023-05-12 13:10 UTC, k-gn commented on core/src/test/java/kr/co/toppings/core/user/service/UserFindServiceTest.java
> +		userUpdateRepository.save(userA);
위에 말씀드린 것 처럼 UserFixture.A,B,C 말고 어떤 의미가 있는 이름이라면 테스트 코드를 보는데 있어서 더 직관적이고 좋을 것 같습니다!

2023-05-13 13:01 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/application/user/service/UserFindService.java
> +	public User findByUserId(Long UserId) {
엇..소나린트를 껐더니 이런 이슈가..ㅎ
수정하겠습니다.

2023-05-13 19:06 UTC, closed without merging

2023-05-13 19:08 UTC, h-beeen commented
해당 작업분 conflict + ServiceTest Error + 전체 함수 네이밍 관련 통합 수정을 위해, develop 브랜치와 동기화 후, PR 코드리뷰분 반영해서 새로 작업하겠습니다.