feat: Spring RestDocs Init / UserSignUpController
toppingskorea/toppings-spring-server pull request #35
Opened 2023-05-24 15:07 UTC by h-beeen

# Describe your changes
- Spring RestDocs 적용을 위한 Config 파일 추가
- Spring RestDocs 적용
- API 정상 호출/응답 확인
- RestDocs -> adoc 변환 성공

## Issue ticket number and link (optional)
#33 
## Checklist

- [ ] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [ ] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?

## Next Step Todo (optional)

## Questions

- 🔥 이건 꼭 확인해주세요!
- 현 코드 1차 목표인 adoc 파일을 생성하여, AsciiDocs 형태로 변환하는 목표를 달성했습니다.
![스크린샷 2023-05-24 오후 11 03 17](https://github.com/toppingskorea/toppings-spring-server/assets/112257466/44b59b37-861c-4a62-aa2c-f2f00ebd16fd)

- 다음과 같은 이슈가 존재합니다.
a. index.adoc, build시 *.adoc파일을 html로 변환해야 하는데, html 아웃풋이 출력되지 않습니다.
  - 예컨데..지금 다중 gradle 환경에서, sourceDirectory를 제대로 못잡는 건가..? 하는 의심이 듭니다.
  - 내지는 build.gradle설정의 문제일 수도 있을 것 같습니다.
  - build시 Task가 실행되지 않는 이슈도 있더라구요. 다중 gradle 환경은 처음이라...어떻게 손을 대야할지 살짝 막막하네요.
![512121](https://github.com/toppingskorea/toppings-spring-server/assets/112257466/d2e7155a-0d17-41f0-a682-de81cf426915)

b. UserController에서 설정한 Constraint가 RestDocs에 출력되지 않습니다.
  - 편의 메소드를 통해 구현한 Attribute.Attribute Constraint가 RestDocs에 반영되지 않습니다.
  - 삽질을 거듭했으나..왜 출력되지 않는지 찾지 못했습니다.

2023-05-24 15:12 UTC, h-beeen commented on api/src/docs/asciidoc/index.adoc
짜잔 새로 등장한 aodc 파일입니다.

index는 전체 API 명세를 제공해주는 adoc파일이며,
adoc파일에서 user, auth(가칭) 등 다양한 컨트롤러의 adoc 파일을 불러옵니다.

2023-05-24 15:13 UTC, h-beeen commented on api/src/docs/asciidoc/user/user.adoc
`user-sign-up-controller-test` -> 클래스 명
`회원가입을_성공한다` -> 메소드 명

해당 클래스의 메소드를 경로로, request와, response에 해당하는 adoc 출력물만을 가져와서 출력합니다.

2023-05-24 15:13 UTC, h-beeen commented on api/src/main/java/kr/co/toppings/api/global/dto/response/Success.java
응답 Success 스펙입니다.

2023-05-24 15:14 UTC, h-beeen commented on api/src/main/java/kr/co/toppings/api/presentation/User/UserSignUpController.java
User 회원가입 API 컨트롤러입니다.
아직 API 스펙은 정한게 없어서, /api/user/{userId} 형식으로 디자인 해봤습니다.

2023-05-24 15:15 UTC, h-beeen commented on api/src/test/java/kr/co/toppings/api/User/UserSignUpControllerTest.java
> +						fieldWithPath("country").description("국적").attributes(constraint("단일 값, Not Null")),
이런 Constraint는 왜 출력이 안되는 걸까요?

2023-05-24 15:16 UTC, h-beeen commented on api/src/test/java/kr/co/toppings/api/global/base/ControllerTestSupport.java
> +@AutoConfigureRestDocs
여러가지 다양한 어노테이션이 활용됩니다.
사실 이해를 100% 하고 사용한 건 아니고, 다양한 레퍼런스 참고하면서, `일단 돌아가라.`라는 마인드로 덕지덕지 발라뒀습니다.

2023-05-24 15:18 UTC, h-beeen commented on api/src/test/java/kr/co/toppings/api/global/config/RestDocsConfig.java
> +	public RestDocumentationResultHandler write(){
ResultHandler입니다. 지금 class-name, method-name을 Path로 Document 하는데, 한글 스펙이 있다 보니, 출력 경로에 한글이 들어갑니다. 필요 시 수정해도 좋을 것 같지만, 저는 그냥 가는것도 좋은 것 같아요.

2023-05-25 00:22 UTC, h-beeen commented on api/src/docs/asciidoc/index.adoc
> +박태하;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
복붙의 폐혜..다음 PR에서 수정하곘습니다 ^^..

2023-05-25 14:11 UTC, k-gn commented on api/src/test/java/kr/co/toppings/api/User/UserSignUpControllerTest.java
> +		BDDMockito.<Long>given(userSignUpService.signUpUser(any())).willReturn(1L);
이 부분 해빈님이 좋아하시는 static import 사용하셔서 given(~).willReturn() 으로 수정하면 더 보기 좋을 것 같습니다!

2023-05-25 14:13 UTC, k-gn requested changes

2023-05-25 14:13 UTC, k-gn commented on api/build.gradle
<img width="1014" alt="Screenshot 2023-05-25 at 11 12 20 PM" src="https://github.com/toppingskorea/toppings-spring-server/assets/77544214/002f5e9e-1e60-4103-b7a0-5d78ad0b75a0">

저는 내용이 이렇게 나오네요!

2023-05-25 14:57 UTC, k-gn requested changes

2023-05-25 14:57 UTC, k-gn commented on api/src/test/java/kr/co/toppings/api/global/base/ControllerTestSupport.java
> +	protected UserSignUpService userSignUpService;
이 위치가 적절한가요?

2023-05-26 04:21 UTC, h-beeen commented on api/build.gradle
맞아요! 그렇게 나오는게 정상이에요. 그런데 adoc 파일을 제대로 파싱해서 긁어오지는 못하는 것 같아요.
저 html이 adoc 파일의 내용을 모두 담아야 할텐데..ㅠㅠ

2023-05-26 04:24 UTC, h-beeen commented on api/src/main/java/kr/co/toppings/api/presentation/User/UserSignUpController.java
패키지 이름은 오타가 맞습니다!
api version도 스펙에 추가하는 것 아주 좋은 의견인 것 같아요!
수정해서 커밋 날리겠습니다!

2023-05-26 04:25 UTC, h-beeen commented on api/src/main/java/kr/co/toppings/api/global/dto/response/Success.java
흠..사실 Redirect를 나중에 추가한다고 하면, 성공 여부만 리턴하면 된다고 판단했습니다.
어떤 추가 정보가 필요할지 조언해주시면 감사할 것 같습니다 :)

2023-05-26 04:29 UTC, h-beeen commented on api/src/test/java/kr/co/toppings/api/global/base/ControllerTestSupport.java
> +	protected UserSignUpService userSignUpService;
음...@MockBean으로 주입한다는 개념이였는데, ControllerTestSupport보다는, 직접 Test 구문에서 주입해주는게 맞을 것 같다는 생각도 들어요! 조금 더 고민해보고, 새로운 커밋에서 수정해 보겠습니다.

2023-05-26 04:30 UTC, h-beeen commented on api/src/test/java/kr/co/toppings/api/User/UserSignUpControllerTest.java
> +	}
엇..? 엇.....? 엇..........?
수정하겠습니다 ^^...

2023-05-26 05:06 UTC, k-gn commented on api/src/main/java/kr/co/toppings/api/global/dto/response/Success.java
음 저는 ApiResponse, ErrorResponse 이렇게 두개를 만들어 사용하는데요!

성공여부와 추가로 httpStatus 상태값, 기타 메시지, 응답할 데이터 이렇게 4개의 데이터를 함께 응답해주곤 했습니다!

지금은 Post 요청을 통해 성공여부만 응답해줄 목적으로 Success 여부만을 확인하고 있지만 나중에 다른 요청이나 body 데이터가 추가적으로 생기게 될 수 있어서요!

httpStatus 상태값, 기타 메시지 같은 정보는 데이터를 받는 입장에서 바로 확인이 가능하기 때문에 추가했습니다!

2023-05-26 05:08 UTC, k-gn commented on api/src/test/java/kr/co/toppings/api/global/base/ControllerTestSupport.java
> +	protected UserSignUpService userSignUpService;
ControllerTestSupport 가 전체 컨트롤러 테스트를 위한 유틸 클래스라고 저는 생각했는데 그렇게 된다면 
UserSignUpService 는 공통으로 쓰이는 필드가 맞을까? 하는 생각이 들어서요!

일단 UserSignUpService 를 사용하는 곳에만 선언하고 추 후 공통으로 사용되는 경우가 늘어난다면 그 때 위치를 다시 고민해봐도 좋을 것 같아 말씀드렸습니다!

2023-05-26 05:09 UTC, k-gn commented on api/build.gradle
해당 브랜치를 제가 따로 파서 이것저것 이슈 삽질좀 해보겠습니다!

2023-05-26 11:03 UTC, k-gn commented on api/src/main/java/kr/co/toppings/api/presentation/User/UserSignUpController.java
아 추가로 UserSignUpController 라고 지으셨는데 컨트롤러도 각각 분리하실 의도이신가요?

2023-05-26 17:23 UTC, h-beeen commented on api/src/main/java/kr/co/toppings/api/global/dto/response/Success.java
좋은 의견인 것 같아요! Response 폼은 말씀주신 4개의 데이터대로 통일하고, 추후 필요하다면, 더 추가하는 방향으로 리팩토링 해도 좋을 것 같습니다!

2023-05-26 17:24 UTC, h-beeen commented on api/src/main/java/kr/co/toppings/api/presentation/User/UserSignUpController.java
@Nested를 활용해서 UserController 내부에서 UserSignUp, UserInfo 등 다양하게 분리하거나, 클래스 자체를 분리해서 단일 기능을 가시적으로 보이게 하고 싶은 생각은 있습니다. 현재는! 후자로 디자인 했습니다.

2023-05-26 17:26 UTC, h-beeen commented on api/src/test/java/kr/co/toppings/api/global/base/ControllerTestSupport.java
> +	protected UserSignUpService userSignUpService;
그쵸 모든 컨트롤러 단에서, SignUp을 가져갈 필요는 없는 것 같아요!
테스트 컨트롤러에서 주입하는 방향으로 가져가는 것이 더 효율적일 것 같네요!!

2023-08-11 08:38 UTC, merged