feat: SignUp Domain / Test (#4)
toppingskorea/toppings-spring-server pull request #7
Opened 2023-05-03 01:05 UTC by h-beeen

# Describe your changes
 - SignUp 도메인 로직 개발
 - dev2.yml 파일 추가
 - 테스트 의존성 관계 추가

## Issue ticket number and link (optional)

## Checklist

- [ ] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [ ] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-05-03 06:56 UTC, k-gn requested changes
1차적으로 리뷰 남겼습니다! 고생하셨습니다!

repository 관련해서 다시 정리해드리자면

infrastructure 영역에 JpaRepository 와 관련 구현체들이 있고, 그걸 사용하는 곳이 application 패키지 입니다. 

단, 직접적으로 사용하게 될 경우 추 후 다른 데이터베이스로 변경된다거나, 테스트용 데이터베이스를 새로 만들고 싶을 때 확장하거나 변경하기 어려워져서 application 영역에 인터페이스를 하나 만들어 두고  infrastructure 에서 구현하는 방식을 사용합니다.

모두가 이렇게 쓰는 건 아니겠지만 현 프로젝트에 적용해보기 적합한 구조라 생각하여 채택하였습니다!

추가로 조회 전용 repository 를 만드신 건 너무너무 좋은 것 같습니다!
(단, repo 는 find, register, modify 이렇게 상세하게 나누실 필요는 없습니다!)

구조상 문제가 있거나, 더 나은 구조가 있다면 언제든지 바로 말씀해주세요!! (대환영)

** 그냥 단순히 중간 테스트를 위해 repository 구조를 조금 수정하신 거라면 OK 입니다!

2023-05-03 06:56 UTC, k-gn commented on core/src/main/java/kr/co/toppings/core/domain/user/UserHabit.java
> +	}
User 에 대한 create static method 에선 new 키워드로 생성하셨는데 여기선 빌더패턴을 사용하신 이유가 있으실까요?

2023-05-03 06:56 UTC, k-gn commented on core/src/main/java/kr/co/toppings/core/application/user/persistence/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
infrastructure 패키지 안에 존재하는 jpa repository를 두고 새로 응용 영역에 만드신 이유가 있나요?

2023-05-03 06:56 UTC, k-gn commented on core/src/main/java/kr/co/toppings/core/infrastructure/user/persistence/UserFindRepository.java
이 repository는 조회를 위한 repository 인가요?

그렇다면 findRepository 보단 UserQueryRepository 라고 하는게 좋을 것 같습니다!
명령(업데이트)과 쿼리(조회)의 역할 분리 관련해서 조회 부분은 Query 라고 하거든요!

2023-05-03 06:57 UTC, k-gn commented
테스트 ci 가 실패된건 한번 확인해보겠습니다~!

2023-05-03 09:22 UTC, h-beeen commented on api/src/main/java/kr/co/toppings/api/presentation/auth/AuthController.java
재사용성을 염두하고, 남겨둔 코드는 아닙니다.
추후, 클라이언트 연동 과정에서 참고하려고 남겨둔 코드인데, 생각보다 지저분하네요 ㅎ
개인 소장 하고 삭제 하겠습니다.

2023-05-03 09:23 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/application/auth/persistence/AuthServiceFacadeImpl.java
사실 아직 퍼사드 패턴에 대한 이해도가 부족한 것 같아요.
AuthController 설계 하던 당시에, 막연하게 짜놓았던 코드입니다.
퍼사드는..패턴을 심도있게 다시 공부해보고 천천히 적용해보는걸로... :)

2023-05-03 09:38 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/domain/user/UserHabit.java
> +	}
빌더패턴으로 createUser 메소드를 설계하면 다음과 같은 오류가 발생했습니다.

Required type:
List <UserHabit>
Provided:
List <Habit>

원래 빌더패턴으로 통일해서 진행하려고 삽질을 좀 해봤었어요. enum타입으로 선언된 Habit 객체와, DB상 UserHabit의 폼을 맞춰주는 과정에서, 빌더 패턴을 적용하면 타입이 맞지 않아 불가피하게 위와 같이 설계했습니다.

2023-05-03 09:40 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/infrastructure/user/persistence/BaseUserRepository.java
> +public class BaseUserRepository {
![스크린샷 2023-05-03 오후 6 40 16](https://user-images.githubusercontent.com/112257466/235882593-61756440-3ed4-4f62-9191-6f3b24c07f42.png)

컴파일 오류로 인해 잠시 제거했었습니다.

2023-05-03 09:42 UTC, h-beeen commented on core/src/main/resources/application.yml
수정하겠습니다.

2023-05-03 09:55 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/infrastructure/user/persistence/UserFindRepository.java
UserJpaRepository로 통합했을 때 단점은 무엇일까요?

2023-05-03 10:03 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/domain/user/User.java
> +    private List<UserHabit> habits = new ArrayList<>();
다시 생각해보니, User와 UserHabit의 생명주기가 동일한 것 같아요. Persist로 저장될 때만 영속성 전이를 시켜도 괜찮지 않을까 생각했는데, User가 삭제되면, UserHabit도 같이 죽는게 맞는 것 같아요! ALL로 수정하겠습니다.

2023-05-03 10:04 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/infrastructure/user/persistence/UserFindRepository.java
굉장히 깔쌈한 이름이군요..bb 바로 수정해보겠습니다.

2023-05-03 12:33 UTC, ChanhyukPark-Tech commented
holy..

2023-05-04 02:14 UTC, k-gn commented on core/src/main/java/kr/co/toppings/core/application/auth/persistence/AuthServiceFacadeImpl.java
그럼 퍼사드 개념을 제외하고 단순히 인터페이스와 구현체로 분리하신 이유는 무엇인가요!

2023-05-04 06:23 UTC, h-beeen reviewed
수정 끝! TC는 나중에 예외 등 추가 사항 작성 후 수정해볼게요!

2023-05-04 06:29 UTC, h-beeen commented on core/src/test/java/kr/co/toppings/core/user/service/UserSignUpTest.java
실패 TC등 상세 TC는 예외 구현 이후, 천천히 진행해 보겠습니다!

2023-05-04 06:33 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/domain/user/User.java
> +    @OneToMany(mappedBy = "user", cascade = ALL, orphanRemoval = true)
이 부분 수정되었습니다!

2023-05-04 06:34 UTC, k-gn requested changes
해빈님 추가로 2차 리뷰 남겼습니다~! 고생하셨습니다!

2023-05-04 06:34 UTC, k-gn commented on core/src/main/java/kr/co/toppings/core/application/user/service/UserSignUpService.java
> +        User saveUser = userQueryRepository.save(user);
조회 용도로 UserQueryRepository 를 만드신거 아니였나요?!

2023-05-04 06:34 UTC, k-gn commented on core/src/main/java/kr/co/toppings/core/domain/user/User.java
>      @Column(name = "user_id")
해빈님은 static import 를 좋아하시는군요! 깔꼼하니 좋네요!

2023-05-04 06:34 UTC, k-gn commented on core/src/main/java/kr/co/toppings/core/infrastructure/user/persistence/BaseUserRepository.java
> +public class BaseUserRepository{
여기 공백 지우신 이유가 있나요?! 
아 그리구 혹시 슬랙에 올린 인텔리제이 코드스타일 적용하셧나욤??

2023-05-04 06:34 UTC, k-gn commented on core/src/main/java/kr/co/toppings/core/infrastructure/user/persistence/BaseUserRepository.java
> +	private final UserQueryRepository userQueryRepository;
UserJpaRepository 를 UserQueryRepository  로 수정하신 것 같은데 
UserFindRepository 를 UserQueryRepository  로 수정해야 하는 것 아닐까요?!

2023-05-04 06:34 UTC, k-gn commented on core/src/main/java/kr/co/toppings/core/domain/user/constants/Country.java
> +    Japan;
전부 대문자로 하는게 좋을 것 같습니다!

2023-05-04 06:34 UTC, k-gn commented on core/src/test/java/kr/co/toppings/core/user/service/UserSignUpTest.java
> +    @DisplayName("[회원가입] 정상 성공")
오홍 훨씬 명확하고 보기 좋네요! 굿입니다!

2023-05-04 06:44 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/infrastructure/user/persistence/BaseUserRepository.java
> +public class BaseUserRepository{
이건..Cmd+Shift+L의 이슈인 것 같네요!
코드스타일도 아직 적용이 안되었는데, 수정해서 3차 수정을 해보도록 하겠습니다!

2023-05-04 06:54 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/domain/user/User.java
>      @Column(name = "user_id")
static import의 간결한 코드는 눈을 편하게 한답니다 :)

2023-05-04 06:55 UTC, h-beeen commented on core/src/main/java/kr/co/toppings/core/infrastructure/user/persistence/BaseUserRepository.java
> +	private final UserQueryRepository userQueryRepository;
BaseUserRepository, UserJpaRepository, UserQueryRepository의 상속관계가 조금 헷갈리네요..

UserJpaRepository는 JpaRepository를 상속받아, User 전체를 대상으로 적용되는 인터페이스이고,

UserQueryRepository는 UserJpaRepository를 상속받아, User의 조회 전용으로 만들려고 구성한 인터페이스라고 생각하고 있습니다. 

그렇다면 BaseUserRepository는 UserQueryRepository, etc...등등으로 구성되어서 라는 생각으로 설계했는데, 그러면 우리는 BaseUserRepository를 인터페이스로 만들어서 가져가야하나...? 저게 굳이 필요할까..? 용도는 뭘까..? 갑자기 자가 질문에 빠져서 헤어나오지 못하는 중입니다 ㅎ

2023-05-04 07:28 UTC, h-beeen reviewed
코드 컨벤션은 적용 아직 안했습니다!

현재 작성한 코드 모두 Approve 된다면, 
코드 컨벤션만 적용해서 수정 후 리뷰 진행하는 것이 
리뷰하시기 편할 것 이라 판단됩니다.

- 인터페이스의 SRP를 준수해 기능을 분할해 개발한다면, 테스트 용이성 및 유지보수 관리 외에 또 어떤 장점이 있을까요? (CRUD 정도는 통합해도 괜찮지 않을까...? 하는 생각이 들면서도..단위테스트가 복잡해지려나..? 하는 생각도 드네요.

infrastructure 영역에 JpaRepository 와 관련 구현체들이 있고, 그걸 사용하는 곳이 application 패키지
application 영역에 인터페이스를 하나 만들어 두고 infrastructure 에서 구현하는 방식

- BaseUserRepository는 UserJpaRepository를 포함해, UserQueryRepository도 같이 final로 주입해줘야 하지 않나요? 이 부분도 개념이 헷갈리는 것 같아요 :(

MVC와 JPA 개념이 많이 부족함을 느끼는 코드였습니다!
김영한 만세! 강의 빨리 밀어보겠습니다!

2023-05-05 17:13 UTC, h-beeen reviewed
이번 PR은 볼륨을 너무 크게 잡은 것 같아요..
다음 PR부터는 훨씬 세분화해서 코드리뷰 부담이 적도록 해보겠습니다.

- Test 디렉토리 구조를 개선했습니다
- Service / Repository / Controller 형태의 추상 클래스를 만들어, 테스트 코드에서 각 계층별로 상속해서 적용할 수 있도록 설계했습니다.
- 공용으로 사용하는 UserFixture를 테스트케이스에 맞게 가공해서 사용할 수 있도록, Utils를 컨트롤러 계층해 추가했습니다.
- 이번 코드 구조 개선을 하면서, Habit에 로직 문제가 있다는 사실을 확인했습니다... Habit에 지금처럼 new ArrayList<>()로 선언해서 넣으면 문제 없이 작동하지만, 하나라도 유저가 식습관을 선택할 경우, JPA save 메소드 호출 과정에서 오류가 발생합니다... JPA 지식이 짧아서 디버깅하다 실패..
- 식습관 문제만 해결 한 이후에, 닉네임 검증 부분을 만들려고 합니다. 이번 돌아오는 주차 회의에서 다룰 소재인 것 같은데, 회원가입 간 검증 로직을 확실하게 해서, 회원가입을 빠르게 마무리 지어보겠습니다~

2023-05-07 01:07 UTC, k-gn approved these changes
고생하셨습니다 해빈님! 마무리 되시면 해당 PR 스쿼시 머지하면 될 것 같네요!

2023-05-07 01:07 UTC, k-gn commented on core/src/test/java/kr/co/toppings/core/global/base/ServiceTest.java
> +
앞으로 만들 서비스를 도와주기 위한 좋은 방법이라고 생각합니다!

대신 ServiceTest 라는 이름보단 ServiceTestSupport 이런 이름이 더 적절해보입니다!

2023-05-07 01:07 UTC, k-gn commented on core/src/test/java/kr/co/toppings/core/user/controller/utils/SignUpRequestUtils.java
> +}
이런 유틸클래스가 앞으로 테스트를 더 편하게 해주겠네요! 굿!

2023-05-07 11:41 UTC, merged